services:
  web:
    build: .
    image: doppleruniversity/yodaspeak
    container_name: yodaspeak
    init: true
    # Environment variables available to the `docker-compose up` created process are only passed
    # through to a container if the envirionment variable name is in the `environment` list for a container.
    # Think of it as container specific object destructuring.
    environment:
      - LOGGING
      - HOSTNAME
      - PORT
      - TRANSLATE_ENDPOINT
      - TLS_CERT
      - TLS_KEY
      - TLS_PORT
      - TRANSLATION_SUGGESTION
      - YODA_TRANSLATE_API_ENDPOINT
      - YODA_TRANSLATE_API_KEY
      - RATE_LIMITING_ENABLED
      - DOPPLER_TOKEN
      - DOPPLER_PROJECT
      - DOPPLER_ENVIRONMENT
      - DOPPLER_CONFIG
    ports:
      - 8080:8080
      - 8443:8443
